name: CYP2D6_ONT_allele_reconstruction
channels:
  - conda-forge
  - bioconda
  - defaults
  - anaconda
dependencies:
  - snakemake-minimal==6.3.0
  - minimap2==2.17
  - samtools==1.7
  - biopython==1.79
  - pandas==1.1.5
  - xlrd==2.0.1
  - conda-forge::scikit-learn==0.24.2
  - porechop==0.2.4
  - bedtools==2.26.0
